import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Urban Livin",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
            <link rel="icon" type="image/png" href="/assets/imgs/logo/favicon.png" />
                <link rel="stylesheet" href="/assets/css/vendor/bootstrap.min.css" />
                <link rel="stylesheet" href="/assets/css/vendor/animate.min.css" />
                <link rel="stylesheet" href="/assets/css/plugins/swiper.min.css" />
                <link rel="stylesheet" href="/assets/css/vendor/magnific-popup.css" />
                <link rel="stylesheet" href="/assets/css/vendor/fontawesome-pro.css" />
                <link rel="stylesheet" href="/assets/css/vendor/spacing.css" />
                <link rel="stylesheet" href="/assets/css/plugins/odometer-theme-default.css" />
                <link rel="stylesheet" href="/assets/css/plugins/carouselTicker.css" />
                <link rel="stylesheet" href="/assets/css/main.css" />
                <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet"/>

            </head>
            <body>
                {children}

                <script src="/assets/js/vendor/jquery-3.7.1.min.js"></script>
                <script src="/assets/js/plugins/waypoints.min.js"></script>
                <script src="/assets/js/vendor/bootstrap.bundle.min.js"></script>
                <script src="/assets/js/plugins/meanmenu.min.js"></script>
                <script src="/assets/js/plugins/odometer.min.js"></script>
                <script src="/assets/js/plugins/swiper.min.js"></script>
                <script src="/assets/js/plugins/wow.js"></script>
                <script src="/assets/js/vendor/magnific-popup.min.js"></script>
                <script src="/assets/js/vendor/type.js"></script>
                <script src="/assets/js/plugins/nice-select.min.js"></script>
                <script src="/assets/js/vendor/jquery-ui.min.js"></script>
                <script src="/assets/js/vendor/jquery.appear.js"></script>
                <script src="/assets/js/plugins/isotope.pkgd.min.js"></script>
                <script src="/assets/js/plugins/imagesloaded.pkgd.min.js"></script>
                <script src="/assets/js/plugins/gsap.min.js"></script>
                <script src="/assets/js/plugins/ScrollTrigger.min.js"></script>
                <script src="/assets/js/plugins/SplitText.js"></script>
                <script src="/assets/js/plugins/tween-max.min.js"></script> 
                <script src="/assets/js/plugins/draggable.min.js"></script>
                <script src="/assets/js/plugins/jquery.carouselTicker.js"></script>
                <script src="/assets/js/vendor/ajax-form.js"></script>
                <script src="/assets/js/plugins/TextPlugin.min.js"></script>
                <script src="/assets/js/main.js"></script>
                {/* <script src="/assets/js/plugins/magiccursor.js"></script> */}
            </body>
        </html>
    );
}
